#!/usr/bin/env node
import { readFileSync } from 'node:fs';
import { formatFailure, runPrePushHook } from '../scripts/pre-push.mjs';

try {
  process.exitCode = runPrePushHook({ input: readFileSync(0, 'utf8') });
} catch (error) {
  process.stderr.write('pre-push: FAIL: ' + formatFailure(error) + '\n');
  process.exitCode = 1;
}
